port: 5000

# The url for this app, also used by `dfe_sign_in`
base_url: https://localhost:5000

# The url for the google doc feedback link (live version)
feedback_link_url: "https://docs.google.com/forms/d/e/1FAIpQLSfhdvlUkg7oxPjl1C6FcJ2pnlc1OQ82r7o3ZMNKthhVAt_h5g/viewform?usp=sf_link"

# The email address for support queries
support_email: becomingateacher@digital.education.gov.uk

dttp:
  back_office_url: https://dttp-dev.crm4.dynamics.com/
  client_id: "application-registration-client-id-from-env"
  scope: "https://dttp-dev.crm4.dynamics.com/.default"
  client_secret: "client-secret-from-env"
  tenant_id: "tenant-id-from-env"
  api_base_url: "api-base-url-from-env"

# Used to add feature flags in the app to control access to certain features.
features:
  home_text: false
  use_ssl: true
  use_dfe_sign_in: true
  enable_feedback_link: true
  basic_auth: true
  trainee_export: true
  import_applications_from_apply: false
  import_courses_from_ttapi: false
  routes:
    early_years_assessment_only: false 
    early_years_graduate_entry: false 
    early_years_graduate_placement: false 
    early_years_undergrad: false 
    provider_led_postgrad: false 
    school_direct_salaried: false 
    school_direct_tuition_fee: false

dfe_sign_in:
  # Our service name
  identifier: rtt
  # URL that the users are redirected to for signing in
  issuer: https://test-oidc.signin.education.gov.uk
  # URL of the users profile
  profile: https://test-profile.signin.education.gov.uk
  # This value must be set otherwise sign in will fail
  secret: secret required value

apply_api:
  base_url: "base-url-from-env"
  auth_token: "auth-token-from-env"

current_recruitment_cycle_year: 2021

jobs:
  poll_delay_hours: 1
  max_poll_duration_days: 4

sidekiq:
  schedule_file: "config/sidekiq_cron_schedule.yml"

pagination:
  records_per_page: 100

cookies:
  default_number_of_days: 182
  cookie_banner_key: viewed_cookie_message

session_store:
  expire_after_days: 30

teacher_training_api:
  base_url: "https://api.publish-teacher-training-courses.service.gov.uk/api/public/v1"

environment:
  name: qa

slack:
  publish_register_alerts_channel: "#twd_publish_register_tech"
